## **Numpy**

In [17]:
#pip install numpy # Instal

In [18]:
#pip show numpy # To know the Library in python package

In [2]:
import numpy

In [3]:
import numpy as np

In [19]:
# dir(np) # All the Directories

In [20]:
#print(np.__doc__) # Documention of Numpy Library

```
arr = np.array([elements])
marr = np.array([[elements],[elements]])
```

In [13]:
python_list = [1,2,3,4,5,6]
numpy_array = np.array(range(1, 7))

python_list_add = [i+2 for i in python_list]

numpy_array_add = numpy_array+2

print(python_list_add, '\n', numpy_array_add)

[3, 4, 5, 6, 7, 8] 
 [3 4 5 6 7 8]


In [15]:
import time

python_list = [1,2,3,4,5,6]
numpy_array = np.array(range(1, 7))

start_time = time.time()
python_list_add = [i+2 for i in python_list]
End_time = time.time()
print(f"Time taken for Python list addition: {End_time - start_time} seconds")

start_time = time.time()
numpy_array_add = numpy_array+2
End_time = time.time()
print(f"Time taken for numpy array addition: {End_time - start_time} seconds")

Time taken for Python list addition: 0.00024318695068359375 seconds
Time taken for numpy array addition: 0.0009496212005615234 seconds


In [16]:
python_list = [1,2,3,4,5,6]
numpy_array = np.array(range(1, 7))

python_list_add = [i+2 for i in python_list]

numpy_array_add = numpy_array+2

import sys
print(sys.getsizeof(python_list_add))
print(numpy_array_add.nbytes)

120
48


In [4]:
arr1 = np.arange(0, 10, 3, dtype='int')
arr1

array([0, 3, 6, 9])

In [6]:
arr2 = np.linspace(0,10, num=5, dtype='float', endpoint=True)
arr2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

<h3><b>NumPy arange vs linspace</b></h3>

<table>
    <tr>
      <th>Feature</th>
      <th><code>np.arange</code></th>
      <th><code>np.linspace</code></th>
    </tr>
    <tr>
      <td>Syntax</td>
      <td><code>numpy.arange([start, ]stop, [step, ]dtype=None)</code></td>
      <td><code>numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)</code></td>
    </tr>
    <tr>
      <td>Start Value</td>
      <td>Specifies the starting value of the sequence.</td>
      <td>Specifies the starting value of the sequence.</td>
    </tr>
    <tr>
      <td>Stop Value</td>
      <td>Specifies the end value, and the sequence will stop before reaching it.</td>
      <td>Specifies the end value, and the sequence may include it depending on <code>endpoint</code>.</td>
    </tr>
    <tr>
      <td>Spacing</td>
      <td>Specifies the spacing between values.</td>
      <td>Specifies the number of evenly spaced samples to generate.</td>
    </tr>
    <tr>
      <td>Endpoint</td>
      <td>By default, the <code>stop</code> value is not included in the array.</td>
      <td>Determines whether the <code>stop</code> value is included in the array.</td>
    </tr>
    <tr>
      <td>Number of Samples (<code>num</code>)</td>
      <td>Not applicable.</td>
      <td>Specifies the number of evenly spaced samples to generate.</td>
    </tr>
    <tr>
      <td>Return Step Size (<code>retstep</code>)</td>
      <td>Not applicable.</td>
      <td>If <code>True</code>, returns the step size between values.</td>
    </tr>
    <tr>
      <td>Data Type (<code>dtype</code>)</td>
      <td>Sets the data type of the output array.</td>
      <td>Sets the data type of the output array.</td>
    </tr>
  </table>

In [7]:
# 1D Array

In [8]:
arr3 = np.array([1,2,3,4])
arr3

array([1, 2, 3, 4])

In [9]:
arr3.shape

(4,)

In [12]:
arr4 = np.ones(shape=(5,), dtype=int)
arr4

array([1, 1, 1, 1, 1])

In [16]:
arr5 = np.zeros(shape=(4), dtype=float)
arr5

array([0., 0., 0., 0.])

In [17]:
# 2D

In [19]:
arr6 = np.array([[1,2,3], [4,5,6]])
arr6

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr6.shape

(2, 3)

In [21]:
arr6.size

6

In [22]:
arr7 = np.ones(shape=(3,2))
arr7

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
arr8 = np.zeros(shape=(2,2), dtype='int')
arr8

array([[0, 0],
       [0, 0]])

In [25]:
#3D

In [26]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
arr9.shape

(2, 2, 2)

In [28]:
arr10 = np.ones(shape=(3,2,2))
arr10

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [29]:
arr10.size

12

In [31]:
arr11 = np.zeros(shape=(2,3,2), dtype=int)
arr11

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [32]:
## Random Module

In [33]:
arr12 = np.random.rand(3,3) # unform ditribution over [0,1]
arr12

array([[0.96117484, 0.44712495, 0.85036826],
       [0.55899637, 0.71840322, 0.84247906],
       [0.47836939, 0.51112716, 0.6570422 ]])

In [35]:
arr13 = np.random.randn(3,3) # Standerd normal distribution over [0,1]
arr13

array([[ 0.2677228 , -1.31435764, -1.55583571],
       [ 0.40585564, -1.79358402,  0.11324689],
       [-0.10043681, -0.40834787,  0.37157766]])

In [36]:
arr14 = np.random.randint(-10,10, size=(2,3)) # Specific Range
arr14

array([[ 7, -1, -6],
       [ 9, -1,  5]], dtype=int32)

In [38]:
## identity 
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
## diagonal
d = np.diag([1,2,3])
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [40]:
## changing the type of the data type

In [41]:
c = np.array([11,12,13], dtype='int')
print(c)

[11 12 13]


In [42]:
# type of array
type(c)

numpy.ndarray

In [43]:
type(c[0])

numpy.int64

In [44]:
g = c.astype(str)
g

array(['11', '12', '13'], dtype='<U21')

In [45]:
type(g[0])

numpy.str_

In [47]:
d = np.linspace(2,10, num=9, dtype=float)
print(d)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [49]:
f = d.astype('int')
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
## Reshape

In [51]:
re = np.arange(0,10)
re

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
re.shape

(10,)

In [55]:
re1 = re.reshape(2,5)
re1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
re2 = np.arange(8).reshape(2,2,2)
re2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
## itemsize and nbytes

In [59]:
its = np.arange(1,13).reshape(4,3)
print(its)

print(its.itemsize) # memory ocupied by the item
print(its.nbytes) # memory ocupied by the array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8
96


In [60]:
## Array Opeartions
### Scalar Opeation

In [61]:
so = np.arange(12).reshape(3,4)
so

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
so+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [64]:
so-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [65]:
so*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [66]:
so /2, # %, //, **

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [1]:
## Vector Operation

In [ ]:
vo = np.array([1,2,3]) + 4 # [5,6,7]
vo1 = np.array([4,5,6])

add = vo + vo1
sub = vo - vo1
mul = vo * vo1
div = vo / vo1
print(add, sub, mul, div, sep=' ')

[ 9 11 13] [1 1 1] [20 30 42] [1.25       1.2        1.16666667]


In [4]:
import numpy as np
za = np.arange(12).reshape(3,4)
zb = np.arange(12,24).reshape(3,4)

print(za, '\n\n', zb)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [5]:
addition = za + zb
subtracion = za - zb
multiplication = za * zb
division = za/zb
addition, subtracion, multiplication, division

(array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]),
 array([[-12, -12, -12, -12],
        [-12, -12, -12, -12],
        [-12, -12, -12, -12]]),
 array([[  0,  13,  28,  45],
        [ 64,  85, 108, 133],
        [160, 189, 220, 253]]),
 array([[0.        , 0.07692308, 0.14285714, 0.2       ],
        [0.25      , 0.29411765, 0.33333333, 0.36842105],
        [0.4       , 0.42857143, 0.45454545, 0.47826087]]))

In [15]:
np.add(za, zb)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [16]:
np.subtract(za, zb)

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [17]:
np.multiply(za, zb)

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [18]:
np.divide(za, zb)

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [19]:
np.mod(za, zb)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.floor_divide(za, zb)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
np.exp(za)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [24]:
## Relational opearion

In [27]:
ro = np.arange(24, 36).reshape(2,6)
ro

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [29]:
ro > 30

array([[False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True]])

In [30]:
ro[ro>30] # Booloean Index

array([31, 32, 33, 34, 35])

In [31]:
ro[ro != 27]

array([24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35])

In [36]:
ro[ro == 30]

array([30])

In [37]:
## Logical Opeartion

In [38]:
lo = np.random.randint(0,100, size=(4,3))
lo

array([[93, 97, 93],
       [92, 55, 79],
       [33, 55, 25],
       [16, 97,  4]], dtype=int32)

In [41]:
And = lo[np.logical_and(lo < 50, lo > 2)]
And

array([33, 25, 16,  4], dtype=int32)

In [47]:
Or = lo[np.logical_or(lo < 50, lo > 200)]
Or

array([33, 25, 16,  4], dtype=int32)

In [49]:
Not = np.logical_not([True])
Not

array([False])

In [51]:
Xor = lo[np.logical_xor(lo < 50, lo > 200)]
Xor

array([33, 25, 16,  4], dtype=int32)

In [52]:
## Aggregate Function

In [53]:
Ao = np.random.randint(20,100, size=(3,3))
Ao

array([[48, 85, 22],
       [38, 75, 62],
       [66, 97, 55]], dtype=int32)

In [55]:
np.sum(Ao, axis=1) # axiz= 1 represents w r t row

array([155, 175, 218])

In [57]:
np.sum(Ao, axis=0) # axiz= 0 represents w r t column

array([152, 257, 139])

In [64]:
np.min(Ao, axis=1)

array([22, 38, 55], dtype=int32)

In [66]:
np.max(Ao)

np.int32(97)

In [71]:
ao1 = np.random.rand(3,3)
ao1

array([[0.97547014, 0.09086102, 0.43138141],
       [0.15158989, 0.03612782, 0.40621857],
       [0.72157672, 0.7568896 , 0.99181224]])

In [72]:
np.round(ao1, 2)

array([[0.98, 0.09, 0.43],
       [0.15, 0.04, 0.41],
       [0.72, 0.76, 0.99]])

In [73]:
np.sqrt(25)

np.float64(5.0)

In [74]:
np.prod(Ao)

np.int64(5584673049120000)

In [75]:
## Statstical Function

In [77]:
Sf = np.random.randn(3,3)
Sf

array([[ 0.26992342, -1.27697075, -0.97605655],
       [ 0.55384567, -1.08737909, -1.30219621],
       [ 0.57585728, -1.07112516, -1.01931896]])

In [83]:
np.mean(Sf)

np.float64(-0.5926022610989397)

In [84]:
np.median(Sf)

np.float64(-1.0193189565323832)

In [93]:
np.std(Sf)

np.float64(0.7599990875521397)

In [90]:
np.var(Sf)

np.float64(0.577598613080085)

In [91]:
np.sqrt(np.var(Sf))

np.float64(0.7599990875521397)

In [94]:
## Log and Exp

In [97]:
np.log10(10000)

np.float64(4.0)

In [98]:
np.log(100)

np.float64(4.605170185988092)

In [111]:
np.log10(1)

np.float64(0.0)

In [108]:
np.log1p(0) # it applies insted zero -> 1

np.float64(0.0)

In [99]:
np.exp(10) # Eulers Number e = 2.718182

np.float64(22026.465794806718)

In [100]:
2.718182**10

22018.377947688605

In [101]:
### Rounding The Elements

In [105]:
arr = np.array([1.253,2.753,3.553,4.939])
rounded_arr = np.round(arr, 2)
rounded_arr

array([1.25, 2.75, 3.55, 4.94])

In [106]:
## Floor

floored_arr = np.floor(arr) # round up to least integer
floored_arr

array([1., 2., 3., 4.])

In [107]:
## Ceil

ceil_arr = np.ceil(arr) # round up to highest integer
ceil_arr

array([2., 3., 4., 5.])

In [1]:
## Set Operation

In [2]:
import numpy as np

In [3]:
m = np.array([1,2,3,4,5,6])
n = np.array([3,4,5,6,7,8])

In [4]:
np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
np.intersect1d(m,n)

array([3, 4, 5, 6])

In [7]:
np.setdiff1d(n,m)

array([7, 8])

In [8]:
## indexing and slicing

In [9]:
idx = np.array([10,20,30,40,50,60,70])

In [10]:
idx[0]

np.int64(10)

In [12]:
idx[1:5]

array([20, 30, 40, 50])

In [14]:
idx[1:]

array([20, 30, 40, 50, 60, 70])

In [17]:
idx[1:6:2]

array([20, 40, 60])

In [19]:
p1 = np.arange(12).reshape(3,4)
p1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
p1[0,1]

np.int64(1)

In [21]:
p1[0:, 0:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [22]:
p1[::2, :4:2]

array([[ 0,  2],
       [ 8, 10]])

In [23]:
p2 = np.arange(8).reshape(2,2,2)
p2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
p2[0]

array([[0, 1],
       [2, 3]])

In [26]:
p2[0,1,0]

np.int64(2)

In [27]:
p2[1,::,::]

array([[4, 5],
       [6, 7]])

In [28]:
## Isin

In [29]:
i = np.arange(10,100,10)
i

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
val = np.array([10,20,100])

np.isin(i, val)

array([ True,  True, False, False, False, False, False, False, False])

In [34]:
i[np.isin(i, val)]

array([10, 20])

In [35]:
np.isin([50,60], i)

array([ True,  True])

In [36]:
## where opearator

In [43]:
wh = np.arange(0,100+1)
wh

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [44]:
np.where(wh<50)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),)

In [45]:
np.where(wh<50, 1, wh)

array([  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [51]:
div3 = np.where(wh%3==0, '3', wh) # bases on the index
div3

array(['3', '1', '2', '3', '4', '5', '3', '7', '8', '3', '10', '11', '3',
       '13', '14', '3', '16', '17', '3', '19', '20', '3', '22', '23', '3',
       '25', '26', '3', '28', '29', '3', '31', '32', '3', '34', '35', '3',
       '37', '38', '3', '40', '41', '3', '43', '44', '3', '46', '47', '3',
       '49', '50', '3', '52', '53', '3', '55', '56', '3', '58', '59', '3',
       '61', '62', '3', '64', '65', '3', '67', '68', '3', '70', '71', '3',
       '73', '74', '3', '76', '77', '3', '79', '80', '3', '82', '83', '3',
       '85', '86', '3', '88', '89', '3', '91', '92', '3', '94', '95', '3',
       '97', '98', '3', '100'], dtype='<U21')

In [52]:
div3.astype('int')

array([  3,   1,   2,   3,   4,   5,   3,   7,   8,   3,  10,  11,   3,
        13,  14,   3,  16,  17,   3,  19,  20,   3,  22,  23,   3,  25,
        26,   3,  28,  29,   3,  31,  32,   3,  34,  35,   3,  37,  38,
         3,  40,  41,   3,  43,  44,   3,  46,  47,   3,  49,  50,   3,
        52,  53,   3,  55,  56,   3,  58,  59,   3,  61,  62,   3,  64,
        65,   3,  67,  68,   3,  70,  71,   3,  73,  74,   3,  76,  77,
         3,  79,  80,   3,  82,  83,   3,  85,  86,   3,  88,  89,   3,
        91,  92,   3,  94,  95,   3,  97,  98,   3, 100])

In [53]:
# max and min value index

In [60]:
am = np.linspace(0,99,num=10, dtype=int).reshape(5,2)
am

array([[ 0, 11],
       [22, 33],
       [44, 55],
       [66, 77],
       [88, 99]])

In [65]:
max_value_index = np.argmax(am)
max_value_index

np.int64(9)

In [64]:
min_value_index = np.argmin(am, axis=0)
min_value_index

array([0, 0])

In [67]:
## iteration array

In [68]:
p1 = np.arange(10)
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
for i in p1:
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [71]:
p2 = np.arange(12).reshape(3,4)
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
for i in p2:
    for j in i:
        print(j, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [75]:
for i in np.nditer(p2):
    if i > 4:
        print(i, end=' ')

5 6 7 8 9 10 11 

In [77]:
p3 = np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
for i in p3:
    for j in i:
        for k in j:
            print(k, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [81]:
for i in np.nditer(p3):
    if i < 13:
        print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [82]:
## Sorting

In [83]:
s = np.random.randint(1,100,20)
s

array([51, 56, 11, 23,  5, 27, 54, 17, 36, 48,  2, 80, 54, 60, 13, 81, 66,
       65, 22, 70], dtype=int32)

In [85]:
sort_s = np.sort(s)
sort_s

array([ 2,  5, 11, 13, 17, 22, 23, 27, 36, 48, 51, 54, 54, 56, 60, 65, 66,
       70, 80, 81], dtype=int32)

In [86]:
dec_order = np.sort(s)[::-1]
dec_order

array([81, 80, 70, 66, 65, 60, 56, 54, 54, 51, 48, 36, 27, 23, 22, 17, 13,
       11,  5,  2], dtype=int32)

In [87]:
dec_order1 = np.flip(np.sort(s))
dec_order1

array([81, 80, 70, 66, 65, 60, 56, 54, 54, 51, 48, 36, 27, 23, 22, 17, 13,
       11,  5,  2], dtype=int32)

In [88]:
s1 = np.random.randint(1,200,16).reshape(4,4)
s1

array([[ 62, 144,  93, 187],
       [101, 148,  97,  65],
       [144, 136, 129,  68],
       [174,  35,  94,  64]], dtype=int32)

In [89]:
np.sort(s1)

array([[ 62,  93, 144, 187],
       [ 65,  97, 101, 148],
       [ 68, 129, 136, 144],
       [ 35,  64,  94, 174]], dtype=int32)

In [90]:
np.sort(s1, axis=0)

array([[ 62,  35,  93,  64],
       [101, 136,  94,  65],
       [144, 144,  97,  68],
       [174, 148, 129, 187]], dtype=int32)

In [91]:
## append

In [92]:
np.append(s1, 1)

array([ 62, 144,  93, 187, 101, 148,  97,  65, 144, 136, 129,  68, 174,
        35,  94,  64,   1])

In [94]:
arr = np.array([1,2,3])
np.append(s1, arr)

array([ 62, 144,  93, 187, 101, 148,  97,  65, 144, 136, 129,  68, 174,
        35,  94,  64,   1,   2,   3])

In [95]:
ap = np.array(range(10))
ap

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
append1 = np.append(ap, arr)
append1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])

In [99]:
## unique

In [100]:
np.unique(append1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
un = np.random.randint(1,10, 12).reshape(3,4)
un

array([[6, 3, 4, 7],
       [5, 2, 9, 9],
       [8, 2, 1, 8]], dtype=int32)

In [102]:
np.unique(un)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [104]:
np.unique_counts(un)

UniqueCountsResult(values=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32), counts=array([1, 2, 1, 1, 1, 1, 1, 2, 2]))

In [105]:
np.unique_values(un)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [106]:
##matrix multiplication

In [108]:
mm = np.array([[1,2],[3,4]])
mm1 = np.array([[5,6],[7,8]])

np.dot(mm, mm1)

array([[19, 22],
       [43, 50]])

In [2]:
## Percentaile
import numpy as np

In [4]:
p = np.array([10,20,30,40,50,60,70,80,90,100])
p

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
np.percentile(p, 100) #maximum

np.float64(100.0)

In [6]:
np.percentile(p, 0) #minimum


np.float64(10.0)

In [7]:
np.percentile(p, 50) #median, Quatile 2

np.float64(55.0)

In [8]:
np.percentile(p, 25) # Quartile 1

np.float64(32.5)

In [9]:
np.percentile(p, 75) # Quartile 3

np.float64(77.5)

In [13]:
np.percentile(p, 40)

np.float64(46.0)

In [14]:
## Delete

In [17]:
de = np.random.randint(1,100,15)
de

array([49, 77, 33, 44, 23, 31, 12, 90, 32, 53, 88, 26, 36, 29,  7],
      dtype=int32)

In [18]:
np.delete(de, 1)

array([49, 33, 44, 23, 31, 12, 90, 32, 53, 88, 26, 36, 29,  7],
      dtype=int32)

In [20]:
deleted = np.delete(de, [0,2,5])
deleted

array([77, 44, 23, 12, 90, 32, 53, 88, 26, 36, 29,  7], dtype=int32)

In [21]:
## array manipulation

In [22]:
am = np.arange(12).reshape(3,4)
am

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.transpose(am)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [24]:
am.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [25]:
# ravel and flatten

In [26]:
np.ravel(am)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
am.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
am.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
am1 = np.arange(8).reshape(2,2,2)
am1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
am1.ravel(), am1.flatten()

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6, 7]))

In [31]:
## Concatination

In [36]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[7,8,9],[10,11,12]])

concat = np.concatenate((arr, arr1), axis=1)
concat

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [37]:
## stacking

In [38]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)

w1, w2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [43]:
h_stack = np.hstack((w1, w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [42]:
v_stack = np.vstack((w1, w2))
v_stack

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
## Splitting

In [54]:
np.vsplit(v_stack, 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [53]:
np.hsplit(h_stack, 4)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [56]:
## Boolean indexing and fancy indexing

In [57]:
arr = np.arange(10,100,10,dtype=int)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
arr> 25

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [59]:
arr[arr> 25]

array([30, 40, 50, 60, 70, 80, 90])

In [61]:
arr[arr%6==0]

array([30, 60, 90])

In [62]:
arr[np.array([0,2,5])] # fancy indexing

array([10, 30, 60])

In [63]:
g = np.random.randint(0,100, 24).reshape(6,4)
g

array([[81, 68, 45, 16],
       [84, 14, 48, 93],
       [44, 82, 59, 79],
       [58, 63, 94, 92],
       [91, 93, 63, 68],
       [17, 13,  7, 19]], dtype=int32)

In [66]:
np.sort(g[g>50])[::-1]

array([94, 93, 93, 92, 91, 84, 82, 81, 79, 68, 68, 63, 63, 59, 58],
      dtype=int32)

In [67]:
g[g%2==0]

array([68, 16, 84, 14, 48, 44, 82, 58, 94, 92, 68], dtype=int32)

In [68]:
g[(g>50) & (g%2==0)]

array([68, 84, 82, 58, 94, 92, 68], dtype=int32)

In [70]:
g[~(g%2==0)] # ~ Not

array([81, 45, 93, 59, 79, 63, 91, 93, 63, 17, 13,  7, 19], dtype=int32)

In [72]:
index = np.array([0,2,3])
g[index]

array([[81, 68, 45, 16],
       [44, 82, 59, 79],
       [58, 63, 94, 92]], dtype=int32)

In [73]:
g

array([[81, 68, 45, 16],
       [84, 14, 48, 93],
       [44, 82, 59, 79],
       [58, 63, 94, 92],
       [91, 93, 63, 68],
       [17, 13,  7, 19]], dtype=int32)

In [76]:
## flip

In [75]:
np.flip(g)

array([[19,  7, 13, 17],
       [68, 63, 93, 91],
       [92, 94, 63, 58],
       [79, 59, 82, 44],
       [93, 48, 14, 84],
       [16, 45, 68, 81]], dtype=int32)

In [84]:
fl = np.arange(10)
fl

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.flip(fl)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
## Array Broadcasting

In [79]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

scalr = 4

result = array + scalr
result

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [82]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([7,8,9])

result1 = arr1 + arr2
result1

array([[ 8, 10, 12],
       [11, 13, 15]])

In [83]:
mul = arr1 * arr2
mul

array([[ 7, 16, 27],
       [28, 40, 54]])

In [88]:
# invers of array

In [90]:
ia = np.array([[4,5],[6,7]])

inverse_array = np.linalg.inv(ia)
inverse_array

array([[-3.5,  2.5],
       [ 3. , -2. ]])

In [91]:
## File Handling Using Numpy

In [92]:
arr = np.random.randint(1,200,20)
arr

array([173,   7,  27, 149,  76, 140, 168,  94, 128,  68,  46, 186, 112,
        16, 117, 192, 181,  91, 131,  20], dtype=int32)

In [93]:
np.save('array.npy', arr)

In [94]:
load_data = np.load('array.npy')
load_data

array([173,   7,  27, 149,  76, 140, 168,  94, 128,  68,  46, 186, 112,
        16, 117, 192, 181,  91, 131,  20], dtype=int32)

In [95]:
np.sort(load_data)

array([  7,  16,  20,  27,  46,  68,  76,  91,  94, 112, 117, 128, 131,
       140, 149, 168, 173, 181, 186, 192], dtype=int32)